### ISSUE TITLE
dastard commander should allow trigger stettings in raw units

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard-commander#14]
I think this should be the default.

**Comment by joefowler** [comment]
I thought that it does allow settings in raw units. ?? I think a simple change to the default index of `levelVoltsRaw` in the Qt Designer and to the text of the relevant labels along the right should accomplish this.

**Comment by joefowler** [comment]
Do you think raw units should be the default? If so, I leave this to you.
