### ISSUE TITLE
send commands called after socket closed

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard-commander#22]
Example output following me pressing the "Quit" button.

```
ZMQListener quit cleanly
Traceback (most recent call last):
  File "/Users/oneilg/python_misc/dastard-commander/trigger_config.py", line 223, in changedAutoTrigConfig
    self.client.call("SourceControl.ConfigureTriggers", state)
  File "/Users/oneilg/python_misc/dastard-commander/rpc_client.py", line 20, in call
    raise Exception("call after socket closed")
Exception: call after socket closed
Abort trap: 6
687gombp:dastard-commander
```

**Comment by joefowler** [comment]
Yes, I've been seeing this _some of the time_ for a while. Thanks for filing. 

We could simply trap and ignore this error, but there is clearly a cause. Specifically, DC is sending the ConfigureTriggers RPC command after we've disconnected. This is stupid and should be ended. (I've had a note in my todo list about it for weeks.)

**Comment by joefowler** [comment]
Aha! Steps to reproduce this are:

1. Connect DC and start a data source (or leave one running if it's already started).
2. Click as if you're going to enter text in the auto-trigger threshold text entry box.
3. With the cursor still editing that text, click Quit or Disconnect.

If I put the cursor in the level trigger threshold box, I get this error:

```text
disconnecting because: disconnect button
ZMQListener quit cleanly
Traceback (most recent call last):
  File "/Users/fowlerj/Software/dastard-commander/trigger_config.py", line 305, in changedLevelTrigConfig
    self.client.call("SourceControl.ConfigureTriggers", state)
  File "/Users/fowlerj/Software/dastard-commander/rpc_client.py", line 20, in call
    raise Exception("call after socket closed")
Exception: call after socket closed
Abort trap: 6
```

This seems to me a funny Qt effect. If you're editing a text entry box, then closing the entire window generates an `editingFinished` event. Ugh! Not sure how to fix it....
