### ISSUE TITLE
trigger ui doesn't update when trigger settings change

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard-commander#23]
What I did:
1. `go run dastard.go`
2. `python dc.py`
3. Start simulated pulse source. 10 channels, 10000 samples/second, 1 amplitude, 10 dc level, 100 samples/pulse.
4. Set autotrigger OFF for all channels with 250 ms delay.
5. Press "Take Noise" in workflow tab, this sends a message to dastard that sets the autotrigger delay to 0 ms and turns auto triggers on.

What I expect:
Looking at the trigger ui tab will show auto trigger on, 0 ms. 
I know it worked though, because the trigger rate went up to 100 cps/channel.

What happens:
Looking at the trigger ui tab shows auto trigger off, delay 250 ms.

**Comment by joefowler** [comment]
Yes, I've had a nagging feeling that there is some error like this, simply because trigger settings don't "save" the way that they should.

I'm assuming that I need branch:workflow to get this to happen...

Another reason you know that "Take noise" worked is that you see this message to the client:

```text
TRIGGER    37: [{u'ChanNumbers': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], u'EdgeFalling': False, u'LevelTrigger': False, u'EdgeLevel': 0, u'EdgeMultiVerifyNMonotone': 0, u'EdgeMultiMakeShortRecords': False, u'EdgeRising': False, u'EdgeMultiMakeContaminatedRecords': False, u'LevelLevel': 0, u'LevelRising': False, u'AutoTrigger': True, u'EdgeTrigger': False, u'AutoDelay': 0, u'EdgeMulti': False}]
```

**Comment by ggggggggg** [comment]
Alternate way to reproduce:
1. Start simulated pulse source. 10 channels, 10000 samples/second, 1 amplitude, 10 dc level, 100 samples/pulse.
2. Change record length to 5.
3. Change autotrigger settings for all channels to off.
4. Stop and Start the source again.
5. The record length will have changed, and the trigger setting will have changed, but the gui will not have changed.

**Comment by joefowler** [comment]
Actually, trigger settings _save_ just fine, but they don't restore to the gui.

Anyway, stand by. I think I have the fix.
