### ISSUE TITLE
Does dc silently add 0.5 ms to auto trigger delay?

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard-commander#33]
See this code, it looks like it adds to autodelay for no reason. Also why they try catch with a pass?  https://github.com/usnistgov/dastard-commander/blob/5408fa82ae1f4f3177571ec7fcfaf347151c9bbf/trigger_config.py#L263

**Comment by ggggggggg** [comment]
The delay number in ms is multiplied by 1e6, so it looks like we're adding 0.5 ns, I'm guessing tihis is to avoid callling ceil? Or round?

**Comment by joefowler** [comment]
Yes. I'll rewrite to be clearer. The name should be `nsdelay` instead of `msdelay`, too.
