### ISSUE TITLE
Problems with triggering on non-TDM (sim pulse) source

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastard-commander#52]
Still trying to learn more about this bug, but you can set up a 1-channel sim pulse source and start it. You'll find that the trigger settings do not lead to an RPC request being sent. Why? @ggggggggg and I noticed this.

**Comment by ggggggggg** [comment]
Jamie noticed that when he went to a 4 channel source, only 3 channels were triggering. Maybe it it somehow skipping channelIndex 0?
