### ISSUE TITLE
NSAMP spin box is too small to read on Lancero tab

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard-commander#56]
This is based on a report from Jamie, he promises to post a picture.

**Comment by cjtitus** [comment]
![dc_spinbox](https://user-images.githubusercontent.com/1413101/55591448-60ed2100-56ea-11e9-9778-a8438d6d31eb.png)
You can see the Error nsamp box is too small to read. It doesn't expand at all when you resize the UI.

**Comment by joefowler** [comment]
Jamie: I cannot reproduce your problem on my Mac or an Ubuntu 18.04 system. I have nevertheless attempted to convince Qt not to do what you were seeing. Please understand that I am a total amateur at Qt layouts, and see if you can give the latest version a try.
