### ISSUE TITLE
Dastard now reads Lancero configuration from the Cringe output

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastard-commander#58]
Dastard is reading Lancero config info from the JSON file that Cringe generates.
See [Dastard PR 138](https://github.com/usnistgov/dastard/pull/138) for more info. We need to:

1. Parse the `LANCERO` message to learn the relevant facts.
2. Change the Qt objects that let the user set the clock speed (50/125 MHz) and the Nsamp value. These Qt objects can remain on the Lancero tab but need to be display-only and not user settable. 
3. We can add objects for other facts learned from the Cringe JSON file.

**Comment by joefowler** [comment]
Galen: can you read this to-do list and verify that #59 meets these conditions? And if so, close this issue?

**Comment by ggggggggg** [comment]
I did 1 and 2, not 3. I think thats enough to close this. Fixed by #59
