### ISSUE TITLE
in observe have a "pause" or "UNIGNORE" button

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard-commander#65]
endre requested the option to go back to the previous state.

tho we may want to handle this just by adding some states up

**Comment by joefowler** [comment]
Do I understand that we have state buttons to:
* Change to a new lettered state, in sequence following whatever went before.
* Change to a state IGNORE.

And the proposal is to add one that will allow you to switch from IGNORE to the previous lettered state?

When you're in state IGNORE, then the "Set state IGNORE" button is useless, right? So perhaps that button should turn into "Return to previous state" when IGNORE=on. In fact, we could replace "Set new state" with "Set next state (D)" where the parentheses are filled with the upcoming state. And the other button could read "Set state IGNORE" if IGNORE=off, and switch to "Reset state (C)" if IGNORE=on and C was the last valid state.

Does this put too much logic into DC? Who tracks the sequence of state labels, anyway? Dastard? Or DC?

**Comment by ggggggggg** [comment]
That makes sense. Right now Dastard Commander just assumes it is the only one manipulating states. It is easy to break this assumption on purpose, not so easy by accident.
