### ISSUE TITLE
Missing python requirements

### ISSUE THREAD

**Issue by DarkTyr** [usnistgov/dastard-commander#67]
Missing a list of python requirements. Even the most basic, which is which version of python to run. Should be part of the install process. Maybe even an Anaconda environment or something.

**Comment by joefowler** [comment]
Well, did you take notes on what you had to install? That would help us to generate this list.

Unfortunately, we're in the middle of switching to Python 3, so being too specific about Python versions might be a problem. But sure, we'll get this sorted out when we get that done.
